services:
  #  =================== Databases ===================

  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: wfiis_bazy_danych
      POSTGRES_PASSWORD: wfiis_bazy_danych
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./init-scripts:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped


  # =================== Prometheus ===================
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - microservices-net
    restart: unless-stopped


  # =================== Grafana ===================
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "9091:3000"
    networks:
      - microservices-net
    restart: unless-stopped


#  ================== Networks ===================
networks:
  microservices-net:
    driver: bridge

#  =================== Volumes ===================
volumes:
  postgres:
  pgadmin:
  mongo: