spring:
  application:
    name: law-firm
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      enabled: true
  datasource:
#    url: jdbc:postgresql://localhost:5432/your_database
    url: jdbc:postgresql://ep-young-wave-61044232.us-east-2.aws.neon.tech/neondb?sslmode=require
    username:  ${DB_USERNAME}
    password:  ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  profiles:
    active: local


storage:
  local:
    base-path: store/
#    base-path: classpath:store/
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
