global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'law-firm'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']

#  docker run -d --name prometheus -p 9090:9090 -v $(pwd)/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus
